### ISSUE TITLE
[1.14.4] Any way to disable Footprint textures when walking?

### ISSUE THREAD

**Issue by Gbergz** [OreCruncher/MobEffects#1]
I found this in the config;

	#Enable Footprint particle effects
	"Enable Footprint Particles" = false

It disabled the Footprints as I wanted but it also disables the enhanced footsteps sounds that I want left on. Intended or a glitch/bug?

MobEffects Version: **0.0.4.0**
SoundControl Version: **0.0.4.0**
Forge Version: **28.1.107**
MC Version: **1.14.4**

**Comment by OreCruncher** [comment]
Yeah.  That's a derp on my part.

**Comment by OreCruncher** [comment]
Pushed 0.0.5.0 to CurseForge.
